-- CONFIGURACION PARA ACTIVAR AUDIT --
-- ALTER SYSTEM SET AUDIT_TRAIL = 'DB, EXTENDED' SCOPE = SPFILE;
-- SHUTDOWN IMMEDIATE;
-- STARTUP;

-- Se ha configurado AUDIT para modificación de citas o sesiones de entrenamiento o se ha creado un Trigger
AUDIT INSERT, UPDATE, DELETE ON CITAS;
AUDIT INSERT, UPDATE, DELETE ON SESIONES;
AUDIT CREATE TRIGGER;