create or replace PACKAGE BASE AS 

    -- Excepciones
    EXCEPCION_CREACION EXCEPTION;
    EXCEPCION_MODIFICACION EXCEPTION;
    EXCEPCION_ELIMINACION EXCEPTION;
    EXCEPCION_LECTURA EXCEPTION;

    -- Tipo de registro para TCLIENTE
    TYPE TCLIENTE IS RECORD (
        NOMBRE USUARIO.NOMBRE%TYPE,
        APELLIDOS USUARIO.APELLIDOS%TYPE,
        TELEFONO USUARIO.TELEFONO%TYPE,
        DIRECCION USUARIO.DIRECCION%TYPE,
        CORREOE USUARIO.CORREOE%TYPE,
        OBJETIVOS CLIENTE.OBJETIVO%TYPE,
        DIETA CLIENTE.DIETA_ID%TYPE,  -- Cambiado a DIETA_ID
        PREFERENCIAS CLIENTE.PREFERENCIAS%TYPE,
        CENTRO CLIENTE.CENTRO_ID%TYPE  -- Cambiado a CENTRO_ID
    );
    
    --Tipo de registro para TENTRENADOR
    
    TYPE TENTRENADOR IS RECORD (
        NOMBRE USUARIO.NOMBRE%TYPE,
        APELLIDOS USUARIO.APELLIDOS%TYPE,
        TELEFONO USUARIO.TELEFONO%TYPE,
        DIRECCION USUARIO.DIRECCION%TYPE,
        CORREOE USUARIO.CORREOE%TYPE,
        DISPONIBILIDAD ENTRENADOR.DISPONIBILIDAD%TYPE,
        CENTRO ENTRENADOR.CENTRO_ID%TYPE -- Cambiado a CENTRO_ID
    );
    
    -- Tipo de registro para TGERENTE

    TYPE TGERENTE IS RECORD (
        NOMBRE USUARIO.NOMBRE%TYPE,
        APELLIDOS USUARIO.APELLIDOS%TYPE,
        TELEFONO USUARIO.TELEFONO%TYPE,
        DIRECCION USUARIO.DIRECCION%TYPE,
        CORREOE USUARIO.CORREOE%TYPE,
        DESPACHO GERENTE.DESPACHO%TYPE,
        HORARIO GERENTE.HORARIO%TYPE,
        CENTRO GERENTE.CENTRO_ID%TYPE -- Cambiado a CENTRO_ID
    );

    -- Procedimiento para crear un cliente
    PROCEDURE CREA_CLIENTE(
        P_DATOS    IN  TCLIENTE,
        P_USERPASS IN  VARCHAR2,
        P_USUARIO  OUT USUARIO%ROWTYPE,
        P_CLIENTE  OUT CLIENTE%ROWTYPE
    );
    
    --Procedimiento para crear un entrenador
    
    PROCEDURE CREA_ENTRENADOR(
        P_DATOS IN TENTRENADOR,
        P_USERPASS IN VARCHAR2,
        P_USUARIO OUT USUARIO%ROWTYPE,
        P_ENTRENADOR OUT ENTRENADOR%ROWTYPE
    );
    
    
    --Procedimiento para crear un gerente
    
    PROCEDURE CREA_GERENTE(
        P_DATOS IN TGERENTE,
        P_USERPASS IN VARCHAR2,
        P_USUARIO OUT USUARIO%ROWTYPE,
        P_GERENTE OUT GERENTE%ROWTYPE
    );
    
    PROCEDURE ELIMINA_USER(P_ID USUARIO.ID%TYPE);
    PROCEDURE ELIMINA_CLIENTE(P_ID USUARIO.ID%TYPE);
    PROCEDURE ELIMINA_GERENTE(P_ID USUARIO.ID%TYPE);
    PROCEDURE ELIMINA_ENTRENADOR(P_ID USUARIO.ID%TYPE); 
    PROCEDURE ELIMINA_CENTRO(P_ID CENTRO.ID%TYPE);
    
END BASE;