CREATE TABLESPACE TS_LIFEFIT DATAFILE "ts_lifefit.dbf" SIZE 1G AUTOEXTEND ON;

-- Hemos dado ___ MB/GB... de quota por tal y tal
CREATE USER LIFEFIT IDENTIFIED BY LIFEFIT123
    DEFAULT TABLESPACE TS_LIFEFIT
    QUOTA 1G ON TS_LIFEFIT;

También para crear secuencias y procedimientos
GRANT CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE SEQUENCE, CREATE PROCEDURE ON TS_LIFEFIT TO LFEFIT;

CREATE TABLESPACE TS_INDICES DATAFILE 'ts_indices.dbf' SIZE 50M AUTOEXTEND ON;

-- Asigna ___ de quota a LIFEFIT por tal y tal
ALTER USER LIFEFIT QUOTA 50M ON TS_INDICES;

