----------------------------------------
-- TODO ESTO SE VA A ELIMINAR ----------
-- YA SE MANEJA DESDE create_user.sql --
----------------------------------------
DROP PUBLIC SYNONYM S_EJERCICIOS;
DROP USER LIFEFIT CASCADE;
DROP TABLESPACE TS_LIFEFIT INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE TS_INDICES INCLUDING CONTENTS AND DATAFILES;