BEGIN
    IF (TABLESPACE = 'TS_LIFEFIT') THEN
        DROP TABLESPACE TS_LIFEFIT;
    END IF

    IF (USER = 'LIFEFIT') THEN
        FOR T IN (SELECT TABLE_NAME FROM USER_TABLES) LOOP
            EXECUTE IMMEDIATE 'DROP TABLE '|| T.TABLE_NAME || ' CASCADE COSNTRAINTS';
        END LOOP;
    END IF;
END;