DROP PUBLIC SYNONYM S_EJERCICIOS;
DROP USER LIFEFIT CASCADE;
DROP TABLESPACE TS_LIFEFIT INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE TS_INDICES INCLUDING CONTENTS AND DATAFILES;

--eliminamos roles
DROP ROLE administrador;
DROP ROLE gerente;
DROP ROLE entrenador_deporte;
DROP ROLE entrenador_nutricion;
DROP ROLE cliente;

--eliminamos secuencias
DROP SEQUENCE S_EJERCICIOS;