-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2024-04-11 13:56:36 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE centro (
    id          UNSIGNED INTEGER NOT NULL,
    nombre      VARCHAR2(20 CHAR) NOT NULL,
    direccion   VARCHAR2(50 CHAR),
    cod_postal  VARCHAR2(7 CHAR),

    CONSTRAINT centro_pk PRIMARY KEY (id) USING INDEX TABLESPACE TS_INDICES
);
-- ALTER TABLE centro ADD CONSTRAINT centro_pk PRIMARY KEY ( id );

CREATE TABLE cita (
    fecha_y_hora    DATETIME NOT NULL,
    entrenador_id   UNSIGNED INTEGER NOT NULL,
    cliente_id      UNSIGNED INTEGER NOT NULL
    modalidad       VARCHAR2(20 CHAR),

    CONSTRAINT cita_pk PRIMARY KEY (fecha_y_hora, entrenador_id) USING INDEX TABLESPACE TS_INDICES,
    CONSTRAINT cita_uk UNIQUE KEY  (cliente_id) USING INDEX TABLESPACE TS_INDICES
);
-- ALTER TABLE cita ADD CONSTRAINT cita_pk PRIMARY KEY ( fechayhora, id );
-- ALTER TABLE cita ADD CONSTRAINT cita_pkv1 UNIQUE ( cliente_id );

CREATE TABLE cliente (
    id           UNSIGNED INTEGER NOT NULL,
    dieta_id     UNSIGNED INTEGER,
    centro_id    UNSIGNED INTEGER NOT NULL,
    objetivo     VARCHAR2(20 CHAR) NOT NULL,
    preferencias VARCHAR2(50 CHAR),

    CONSTRAINT cliente_pk PRIMARY KEY (id) USING INDEX TABLESPACE TS_INDICES
);
-- ALTER TABLE cliente ADD CONSTRAINT cliente_pk PRIMARY KEY ( id );

CREATE TABLE conforman (
    rutina_id    UNSIGNED INTEGER NOT NULL,
    ejercicio_id UNSIGNED INTEGER NOT NULL,
    series       UNSIGNED NUMBER(4, 0),
    repeticiones UNSIGNED NUMBER(4, 0),     -- SE DECLARA COMO NUMBER PORQUE ADEMÁS VAMOS A HACER ESTADÍSTICAS CON ESTOS DATOS, COMPARARLOS, ETC.
    duracion     UNSIGNED NUMBER(5, 0),     -- EN EL APP HACER OPERACIONES DE CONVERSIÓN DE TIEMPO -- TIENES 5 CIFRAS DECIMALES PARA GUARDAR EL TIEMPO, ES DECIR 99.999 SEGUNDOS O 27.78 HORAS QUE PUEDE DURAR UN ENTRENAMIENTO, EN UN PRINCIPIO LA IDEA ERA PODER ALMACENAR ENRENAMIETNOS DE 5H, SIN EMBARGO, PARA LAMACENAR ESA CANTIDAD NECESITAMOS 5 DIGITOS Y POR TANTO LA COTA SUBE A ESA MAYOR CANTIDAD DE HORAS

    CONSTRAINT conforman_pk PRIMARY KEY (rutina_id, ejercicio_id)
);
-- ALTER TABLE conforman ADD CONSTRAINT conforman_pk PRIMARY KEY ( rutina_id, ejercicio_id );

CREATE TABLE dieta (
    id          UNSIGNED INTEGER NOT NULL,
    nombre      VARCHAR2(20 CHAR) NOT NULL,
    descripcion VARCHAR2(50 CHAR),
    tipo        VARCHAR2(10 CHAR),

    CONSTRAINT dieta_pk PRIMARY KEY (id) USING INDEX TABLESPACE TS_INDICES,
    CONSTRAINT dieta_nombre_uk UNIQUE KEY USING INDEX TABLESPACE TS_INDICES 
);
-- ALTER TABLE dieta ADD CONSTRAINT dieta_pk PRIMARY KEY ( id );
-- ALTER TABLE dieta ADD CONSTRAINT dieta_nombre_un UNIQUE ( nombre );

CREATE TABLE ejercicio (
    id          UNSIGNED INTEGER NOT NULL,
    nombre      VARCHAR2(20 CHAR) NOT NULL,
    descripcion VARCHAR2(255),
    video       BLOB,
    imagen_url  VARCHAR2(511), 

    CONSTRAINT ejercicio_pk PRIMARY KEY (id) USING INDEX TABLESPACE TS_INDICES
);
-- ALTER TABLE ejercicio ADD CONSTRAINT ejercicio_pk PRIMARY KEY ( id );

CREATE TABLE elem_calend (
    fecha_y_hora    DATETIME NOT NULL,
    entrenador_id   UNSIGNED INTEGER NOT NULL,

    CONSTRAINT elem_calend_pk PRIMARY KEY (fecha_y_hora, entrenador_id)
);
-- ALTER TABLE elementocalendario ADD CONSTRAINT elementocalendario_pk PRIMARY KEY ( fechayhora, entrenador_id );

CREATE TABLE entrena (
    cliente_id    UNSIGNED INTEGER NOT NULL,
    entrenador_id UNSIGNED INTEGER NOT NULL,
    especialidad  VARCHAR2(20 CHAR),

    CONSTRAINT entrena_pk PRIMARY KEY (cliente_id, entrenador_id)
);
-- ALTER TABLE entrena ADD CONSTRAINT entrena_pk PRIMARY KEY ( cliente_id, entrenador_id );

CREATE TABLE entrenador (
    id             UNSIGNED INTEGER NOT NULL,
    centro_id      INTEGER NOT NULL,
    disponibilidad VARCHAR2(20 CHAR),

    CONSTRAINT entrenador_pk PRIMARY KEY (id) USING INDEX TABLESPACE TS_INDICES -- defino el tablespace, aun cogiendolo de user??
);
-- ALTER TABLE entrenador ADD CONSTRAINT entrenador_pk PRIMARY KEY ( id );

CREATE TABLE gerente (
    id        UNSIGNED INTEGER NOT NULL,
    centro_id UNSIGNED INTEGER NOT NULL,
    despacho  VARCHAR2(12 CHAR),
    horario   VARCHAR2(20 CHAR),

    CONSTRAINT gerente_pk PRIMARY KEY (id) USING INDEX TABLESPACE TS_INDICES, -- tengo que declarar el tablespace si la pk es una fk?
    CONSTRAINT gerente_idx UNIQUE KEY (centro_id) ASC USING INDEX TABLESPACE TS_INDICES -- ASC WORKS?
);
-- CREATE UNIQUE INDEX gerente__idx ON
--     gerente ( centro_id ASC );

-- ALTER TABLE gerente ADD CONSTRAINT gerente_pk PRIMARY KEY ( id );

CREATE TABLE plan (
    inicio      VARCHAR2(20 CHAR) NOT NULL,
    fin         VARCHAR2(20 CHAR),
    rutina_id   INTEGER NOT NULL,
    entrena_id  VARCHAR2(10 CHAR) NOT NULL,
    -- entrena_id1 VARCHAR2(10 CHAR) NOT NULL,  -- CREO QUE ESTA POR LA CARA

    CONSTRAINT plan_pk PRIMARY KEY (inicio, rutina_id) USING INDEX TABLESPACE TS_INDICES
);
-- ALTER TABLE plan ADD CONSTRAINT plan_pk PRIMARY KEY ( inicio, rutina_id );

CREATE TABLE rutina (
    id          UNSIGNED INTEGER NOT NULL,
    nombre      VARCHAR2(20 CHAR) NOT NULL,
    descripcion VARCHAR2(255),

    CONSTRAINT rutina_pk PRIMARY KEY (id) USING INDEX TABLESPACE TS_INDICES
);
-- ALTER TABLE rutina ADD CONSTRAINT rutina_pk PRIMARY KEY ( id );

CREATE TABLE sesion (
    inicio         DATETIME NOT NULL,
    fin            DATETIME,
    presencial     UNSIGNED NUMBER(1,0),
    descripcion    VARCHAR2(50 CHAR),
    video          BLOB,
    datos_salud    VARCHAR2(100 CHAR),
    plan_inicio    VARCHAR2(20 CHAR) NOT NULL,
    plan_rutina_id UNSIGNED INTEGER NOT NULL,

    CONSTRAINT sesion_pk PRIMARY KEY (plan_inicio, plan_rutina_id) USING INDEX TABLESPACE TS_INDICES,
    CONSTRAINT sesion_presenc_ck CHECK (presencial IN (0,1))
);
-- ALTER TABLE sesion ADD CONSTRAINT sesion_pk PRIMARY KEY ( plan_inicio, plan_rutina_id );

CREATE TABLE usuario (
    id              UNSIGNED INTEGER NOT NULL,
    nombre          VARCHAR2(10 CHAR) NOT NULL,
    apellidos       VARCHAR2(25 CHAR) NOT NULL,
    telefono        VARCHAR2(12 CHAR) NOT NULL,
    direccion       VARCHAR2(32 CHAR),
    correo_e        VARCHAR2(25 CHAR),
    usuario_oracle  VARCHAR2(10 CHAR),

    CONSTRAINT usuario_pk PRIMARY KEY (id) USING INDEX TABLESPACE TS_INDICES
);

ALTER TABLE cita
    ADD CONSTRAINT cita_cliente_fk FOREIGN KEY ( cliente_id )
        REFERENCES cliente ( id );

ALTER TABLE cita
    ADD CONSTRAINT cita_elementocalendario_fk FOREIGN KEY ( fechayhora,
                                                            id )
        REFERENCES elementocalendario ( fechayhora,
                                        entrenador_id );

ALTER TABLE cliente
    ADD CONSTRAINT cliente_centro_fk FOREIGN KEY ( centro_id )
        REFERENCES centro ( id );

ALTER TABLE cliente
    ADD CONSTRAINT cliente_dieta_fk FOREIGN KEY ( dieta_id )
        REFERENCES dieta ( id );

ALTER TABLE cliente
    ADD CONSTRAINT cliente_usuario_fk FOREIGN KEY ( id )
        REFERENCES usuario ( id );

ALTER TABLE conforman
    ADD CONSTRAINT conforman_ejercicio_fk FOREIGN KEY ( ejercicio_id )
        REFERENCES ejercicio ( id );

ALTER TABLE conforman
    ADD CONSTRAINT conforman_rutina_fk FOREIGN KEY ( rutina_id )
        REFERENCES rutina ( id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE elementocalendario
    ADD CONSTRAINT elementocalendario_entrenador_fk FOREIGN KEY ( entrenador_id )
        REFERENCES entrenador ( id );

ALTER TABLE entrena
    ADD CONSTRAINT entrena_cliente_fk FOREIGN KEY ( cliente_id )
        REFERENCES cliente ( id );

ALTER TABLE entrena
    ADD CONSTRAINT entrena_entrenador_fk FOREIGN KEY ( entrenador_id )
        REFERENCES entrenador ( id );

ALTER TABLE entrenador
    ADD CONSTRAINT entrenador_centro_fk FOREIGN KEY ( centro_id )
        REFERENCES centro ( id );

ALTER TABLE entrenador
    ADD CONSTRAINT entrenador_usuario_fk FOREIGN KEY ( id )
        REFERENCES usuario ( id );

ALTER TABLE gerente
    ADD CONSTRAINT gerente_centro_fk FOREIGN KEY ( centro_id )
        REFERENCES centro ( id );

ALTER TABLE gerente
    ADD CONSTRAINT gerente_usuario_fk FOREIGN KEY ( id )
        REFERENCES usuario ( id );

ALTER TABLE plan
    ADD CONSTRAINT plan_entrena_fk FOREIGN KEY ( entrena_id,
                                                 entrena_id1 )
        REFERENCES entrena ( cliente_id,
                             entrenador_id );

ALTER TABLE plan
    ADD CONSTRAINT plan_rutina_fk FOREIGN KEY ( rutina_id )
        REFERENCES rutina ( id );

ALTER TABLE sesion
    ADD CONSTRAINT sesion_plan_fk FOREIGN KEY ( plan_inicio,
                                                plan_rutina_id )
        REFERENCES plan ( inicio,
                          rutina_id );

--  ERROR: No Discriminator Column found in Arc FKArc_1 - constraint trigger for Arc cannot be generated 

--  ERROR: No Discriminator Column found in Arc FKArc_1 - constraint trigger for Arc cannot be generated 

--  ERROR: No Discriminator Column found in Arc FKArc_1 - constraint trigger for Arc cannot be generated



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            14
-- CREATE INDEX                             1
-- ALTER TABLE                             33
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   7
-- WARNINGS                                 0
