BEGIN
    IF (USER = 'LIFEFIT') THEN
        FOR T IN (SELECT TABLE_NAME FROM USER_TABLES) LOOP
            EXECUTE IMMEDIATE 'DROP TABLE '|| T.TABLE_NAME || ' CASCADE CONSTRAINTS';
        END LOOP;
    END IF;
END;
/